#!/bin/bash
set -e

composer install --prefer-dist --no-progress --no-suggest --no-interaction -o

# Permissions hack because setfacl does not work on Mac and Windows
chown -R www-data var

# Continue by running original entrypoint
docker-php-entrypoint $@
