#!/bin/bash
set -e

composer install --prefer-dist --no-progress --no-interaction -o
php bin/console assets:install

# Permissions hack because setfacl does not work on Mac and Windows
chmod -R 777 var

# Continue by running original entrypoint
docker-php-entrypoint $@
