#!/bin/bash
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- apache2-foreground "$@"
fi

php bin/console assets:install

if [[ -v DATABASE_HOST ]]; then
    ## Create DB
    # database is created inside automatically by using "services > mysql > environment > MYSQL_DATABASE" in docker-composer.yml, see https://hub.docker.com/_/mysql

    ## Wait until database connection is ready
    until mysql -u $DATABASE_USER -h $DATABASE_HOST --password="$DATABASE_PASSWORD" -e "" ; do
        >&2 echo "Waiting for database service to start."
        sleep 3
    done

    ## Update DB
    php bin/console doctrine:schema:update --dump-sql --force
fi

## Because this entrypoint is called as root, it will create /var/cache/prod owned by ROOT
chmod -R 777 var/cache

exec "$@"
