#!/bin/bash
set -e

composer install --prefer-dist --no-progress --no-interaction --ignore-platform-req php -o
php bin/console assets:install

# Permissions hack because setfacl does not work on Mac and Windows
chown -R www-data var

# Continue by running original entrypoint
docker-php-entrypoint $@
