name: Demo Runner Test

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    demo_runner_test:
        name: Demo Runner Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
