name: Demo Runner Test

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    demo_runner_test:
        name: Demo Runner Test
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   run: composer install --no-progress --ansi
                working-directory: demo-runner

            -   name: Set bref JSON input
                id: set
                run: |
                    echo ::set-output name=json_var::'[{ "content": "<?php namespace Demo; class AnotherClass {};", "config": <?php ;" }]'

            # test bref command
            -   run: vendor/bin/bref local main ${{ steps.set.outputs.json_var}}
                working-directory: demo-runner
